package dummy.exception;

/* Automatically generated by EVS JavaCodeGenerator */

public class DummyException extends evs.exception.RemotingException {

	private static final long serialVersionUID = 1L;

	public DummyException(){
		super();
	}

	public DummyException(String message){
		super(message);
	}
}
