package evsbsp.server;

import evs.core.ARemoteObject;
import evs.interfaces.IACT;
import evsbsp.IDummyOperations;

/* Automatically generated by EVS JavaCodeGenerator */


public class Dummy extends ARemoteObject implements IDummyOperations  {

    private static final long serialVersionUID = 3420679641630036612L;
	private Integer counter;
	
	public Dummy(){
		/* Auto-Generated Constructor */
		this.objectId = Dummy.class.getName();
		this.counter = 0;
	}

	public Object testCall(Integer a, IACT act) throws evsbsp.exception.DummyException{
		/* Auto-Generated Method Stub */ 
		System.out.println("----------------- testCall called with parameter=" + a + ", countervalue=" + this.counter);
		this.counter += a;
		return null;
	}

	public Integer getCounter(IACT act) throws evsbsp.exception.DummyException{
		/* Auto-Generated Method Stub */ 
		System.out.println("----------------- getCounter called, countervalue=" + this.counter);
		return this.counter;
	}

}
