package evsbsp.server;

/* Automatically generated by EVS JavaCodeGenerator */

import evs.core.ARemoteObject;
import evsbsp.IDummyOperations;

public class Dummy extends ARemoteObject implements IDummyOperations  {
	private Integer counter;
	
	public Dummy(){
		/* Auto-Generated Constructor */
		this.objectId = Dummy.class.getName();
		this.counter = 0;
	}

	public void testCall(Integer a) throws evsbsp.exception.DummyException{
		/* Auto-Generated Method Stub */ 
		System.out.println("----------------- testCall called with parameter=" + a + ", countervalue=" + this.counter);
		this.counter += a;
	}

	public Integer getCounter() throws evsbsp.exception.DummyException{
		/* Auto-Generated Method Stub */ 
		System.out.println("----------------- getCounter called, countervalue=" + this.counter);
		return this.counter;
	}

}
