package evsbsp.server;

/* Automatically generated by EVS JavaCodeGenerator */
import java.util.ArrayList;
import java.util.List;

import evsbsp.entities.Customer;
import evsbsp.entities.Product;
import evs.core.ARemoteObject;
import evs.exception.NotSupportedException;
import evs.interfaces.IACT;
import evsbsp.IEcommerceOperations;

public class Ecommerce extends ARemoteObject implements IEcommerceOperations {

    private static final long serialVersionUID = 1L;
    private static Ecommerce server;
    private int customerSequence = 0;
    private int productSequence = 0;
    private List<Customer> customers;
    private List<Product> products;

    public Ecommerce () {
        /* Auto-Generated Constructor */
        this.objectId = Ecommerce.class.getName ();
        customers = new ArrayList<Customer> ();
        products = new ArrayList<Product> ();
    }

    public Object buyOrder (evsbsp.entities.Order order, IACT act) throws NotSupportedException {
        /* Auto-Generated Method Stub */
        for (Customer customer : customers) {
            if (customer.getId () == customer.getId ()) {
                customer.addOrder (order);
            }
        }
        return null;
    }

    public Object createCustomer (evsbsp.entities.Customer customer, IACT act) throws NotSupportedException {
        /* Auto-Generated Method Stub */
        customer.setId (customerSequence);
        customers.add (customer);
        ++customerSequence;
        return null;
    }

    public Object createProduct (evsbsp.entities.Product product, IACT act) throws NotSupportedException {
        /* Auto-Generated Method Stub */
        product.setId (productSequence);
        products.add (product);
        ++productSequence;
        return null;
    }

    public Object listProducts (IACT act) throws NotSupportedException {
        /* Auto-Generated Method Stub */
        return products;
    }

    public Object login (String userName, String password, IACT act) throws NotSupportedException {
        /* Auto-Generated Method Stub */
        for (Customer customer : customers) {
            if (customer.getUserName ().equals (userName) && customer.getPassword ().equals (password)) {
                return customer;
            }
        }
        return null;
    }

    public Object updateCustomer (evsbsp.entities.Customer customer, IACT act) throws NotSupportedException {
        /* Auto-Generated Method Stub */
        for (Customer cust : customers) {
            if (customer.getId () == customer.getId ()) {
                cust.setName (customer.getName ());
                cust.setUserName (customer.getUserName ());
                cust.setPassword (customer.getPassword ());
            }
        }
        return null;
    }

    public Object updateProduct (evsbsp.entities.Product product, IACT act) throws NotSupportedException {
        /* Auto-Generated Method Stub */
        for (Product prod : products) {
            if (product.getId () == prod.getId ()) {
                prod.setName (product.getName ());
                prod.setPrice (product.getPrice ());
            }
        }
        return null;
    }

    public static Ecommerce getInstance () {
        if (server == null) {
            server = new Ecommerce ();
        }
        return server;
    }
}
