package dummy.server;

/* Automatically generated by EVS JavaCodeGenerator */

import dummy.IDummyOperations;
import evs.interfaces.IACT;
import evs.core.ARemoteObject;
import evs.exception.NotSupportedException;

public class Dummy extends ARemoteObject implements IDummyOperations{

	private static final long serialVersionUID = 1L;
	private Integer counter;

	public Dummy(){
		/* Auto-Generated Constructor */
		this.objectId = Dummy.class.getName();
		this.counter = 0;
	}

	public Object testCall(Integer a, IACT act) throws dummy.exception.DummyException, NotSupportedException{
		/* Auto-Generated Method Stub */ 
		System.out.println("----------------- testCall called with parameter=" + a + ", countervalue=" + this.counter);
		this.counter += a;
		return null;
	}

	public Object getCounter(IACT act) throws dummy.exception.DummyException, NotSupportedException{
		/* Auto-Generated Method Stub */ 
		System.out.println("----------------- getCounter called, countervalue=" + this.counter);
		return this.counter;
	}

}

