package evs.example.client;

/* Automatically generated by EVS JavaCodeGenerator */

import java.util.ArrayList;

import evs.comm.exception.NotSupportedException;
import evs.comm.exception.RemotingException;
import evs.comm.impl.AClientProxy;
import evs.comm.impl.AOR;
import evs.comm.impl.InvocationObject;
import evs.comm.impl.ObjectReference;
import evs.comm.impl.WebLocation;
import evs.comm.interfaces.IInvocationObject;
import evs.example.IDummyOperations;
import evs.example.exception.DummyException;

public class DummyProxy extends AClientProxy implements IDummyOperations  {
	
	//automatically generated default values
	private static final String INVOKER_ID = evs.example.server.DummyInvoker.class.getName();
	private static final String OBJECT_ID = evs.example.server.Dummy.class.getName(); 
	private static final String HOSTNAME = "localhost";
	private static final String PORT = "1337";
	
	public DummyProxy(){
		super();
		this.aor = new AOR(new WebLocation(HOSTNAME, PORT), new ObjectReference(OBJECT_ID, INVOKER_ID));
	}
	
	public void testCall(Integer a) throws DummyException, NotSupportedException{
		ArrayList<Object> arguments = new ArrayList<Object>();
		arguments.add(a);
		try{
			IInvocationObject object = new InvocationObject(getAOR(), "testCall", arguments, "void");
			requestor.invoke(object, true);
		} catch(RemotingException ex){
			 if(ex instanceof DummyException) throw (DummyException) ex;
			 if(ex instanceof NotSupportedException) throw (NotSupportedException) ex;
			 System.out.println("[x] ERROR: " + ex.getClass().getName() + " :" + ex.getMessage());
			 ex.printStackTrace();
		}
	}

	public Integer getCounter() throws DummyException, NotSupportedException{
		ArrayList<Object> arguments = new ArrayList<Object>();
		try{
			IInvocationObject object = new InvocationObject(getAOR(), "getCounter", arguments, "Integer");
			return (Integer) requestor.invoke(object, false);
		} catch(RemotingException ex){
			 if(ex instanceof DummyException) throw (DummyException) ex;
			 if(ex instanceof NotSupportedException) throw (NotSupportedException) ex;
			 System.out.println("[x] ERROR: " + ex.getClass().getName() + " :" + ex.getMessage());
			 ex.printStackTrace();
		}
		return null;
	}

}
