package evs.example;

import evs.comm.exception.NotSupportedException;

/* Automatically generated by EVS JavaCodeGenerator */

public interface IDummyOperations {
	public void testCall(Integer a) throws evs.example.exception.DummyException, NotSupportedException;
	public Integer getCounter() throws evs.example.exception.DummyException, NotSupportedException;
}
