package evsbsp.exception;

/* Automatically generated by EVS JavaCodeGenerator */

public class DummyException extends evs.exception.RemotingException {

    private static final long serialVersionUID = -7895063636696531151L;

	public DummyException(){
		super();
	}

	public DummyException(String message){
		super(message);
	}
}
