package evsbsp.exception;

/* Automatically generated by EVS JavaCodeGenerator */

public class DummyException extends evs.exception.RemotingException {

	public DummyException(){
		super();
	}

	public DummyException(String message){
		super(message);
	}
}
