package evsbsp;

import evs.exception.NotSupportedException;
import evs.interfaces.IACT;

/* Automatically generated by EVS JavaCodeGenerator */

public interface IDummyOperations {
	public Object testCall(Integer a, IACT act) throws evsbsp.exception.DummyException, NotSupportedException;
	public Object getCounter(IACT act) throws evsbsp.exception.DummyException, NotSupportedException;
}
