package evsbsp;

import evs.exception.NotSupportedException;

/* Automatically generated by EVS JavaCodeGenerator */

public interface IDummyOperations {
	public void testCall(Integer a) throws evsbsp.exception.DummyException, NotSupportedException;
	public Integer getCounter() throws evsbsp.exception.DummyException, NotSupportedException;
}
