package evsbsp;

import evs.exception.NotSupportedException;
import evs.interfaces.IACT;
import evs.interfaces.ICallback;

/* Automatically generated by EVS JavaCodeGenerator */

public interface IDummyOperations {
	public void testCall(Integer a, IACT act) throws evsbsp.exception.DummyException, NotSupportedException;
	public Integer getCounter(IACT act) throws evsbsp.exception.DummyException, NotSupportedException;
}
