package evs.example.server;

/* Automatically generated by EVS JavaCodeGenerator */

import evs.comm.impl.ARemoteObject;
import evs.example.IDummyOperations;

public class Dummy extends ARemoteObject implements IDummyOperations  {
	private Integer counter;
	
	public Dummy(){
		/* Auto-Generated Constructor */
		this.objectId = Dummy.class.getName();
	}

	public void testCall(Integer a) throws evs.example.exception.DummyException{
		/* Auto-Generated Method Stub */ 
		System.out.println("----------------- testCall called with parameter=" + a + ", countervalue=" + this.counter);
		this.counter += a;
	}

	public Integer getCounter() throws evs.example.exception.DummyException{
		/* Auto-Generated Method Stub */ 
		System.out.println("----------------- getCounter called, countervalue=" + this.counter);
		return this.counter;
	}

}
